# Generated by Django 2.0.1 on 2018-01-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='imgId',
            field=models.CharField(default='adsf', max_length=255),
            preserve_default=False,
        ),
    ]
